/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 */

import type { APIRequest } from '@pipecat-ai/client-js';

// export type TransportType = 'daily' | 'smallwebrtc';

export type TransportType = 'smallwebrtc';

export const AVAILABLE_TRANSPORTS: TransportType[] = [
  // 'daily',
  'smallwebrtc',
];

export const DEFAULT_TRANSPORT: TransportType = 'smallwebrtc';

export const BOT_NAME = process.env.NEXT_PUBLIC_BOT_NAME || 'AI Interviewer';

const botStartUrl = process.env.BOT_START_URL || 'http://localhost:7860/start';
export const BOT_API_URL = botStartUrl.replace(/\/start$/, '');

export const TRANSPORT_CONFIG: Record<TransportType, APIRequest> = {
  // daily: {
  //   endpoint: '/api/start',
  //   requestData: {
  //     createDailyRoom: true,
  //     dailyRoomProperties: { start_video_off: true },
  //   },
  // },
  smallwebrtc: {
    endpoint: '/api/start',
    requestData: {
      createDailyRoom: false,
      enableDefaultIceServers: true,
    },
  },
};